### ISSUE TITLE
Carthage build 

### ISSUE THREAD

**Issue by anhbontb** [acrocat/EverLayout#3]
Hi !
I run:

 carthage update --platform iOS

and receive output message: 

Dependency "EverLayout" has no shared framework schemes for any of the platforms: iOS

Please check config.

Thank you.

**Comment by acrocat** [comment]
Thanks for pointing this out.

I've been having a hard time getting Carthage and Ccoapods to play nicely with EL having a dependency, so this encouraged me to finally get rid of Socket.IO. 

I've rearranged the directory a bit in v0.9.1 so that Carthage should work now, let me know if there are still problems.

**Comment by anhbontb** [comment]
Thank you !

Carthage update look ok. but I received errror messsage after import EverLayout

.../CashBackPopup/ZPCashbackPopupViewController.swift:13:8: Module file's minimum deployment target is ios10.3 v10.3: .../Carthage/Build/iOS/EverLayout.framework/Modules/EverLayout.swiftmodule/arm64.swiftmodule

I using xcode 8.3 target to ios 8.0.

**Comment by acrocat** [comment]
Ah I forgot the set the target version to 8.0.

Version 0.9.3 should absolutely, 100% work this time ;)
